# Theme Integration
include ~/.config/i3-themes/current/theme/kitty.conf

# Font
font_family      CaskaydiaMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 9.0

# Window
window_padding_width 14

# Keybindings
map shift+insert paste_from_clipboard
map ctrl+insert  copy_to_clipboard
